### ISSUE TITLE
原汉化文件被本模组汉化覆盖和一个错误。

### ISSUE THREAD

**Issue by xinpingqihe-44** [LangYueMc/AutoTranslation#1]
装本模组启动游戏一切正常，一旦重启游戏，本模组的汉化内容文本就会把原模组的汉化文本给覆盖掉，并且如果模组配置里面的追加原始文本这条设置是是的话，游戏的数值都会显示错误直接显示成%s，改否就能显示出正确的数值。

**Comment by xinpingqihe-44** [comment]
游戏版本是1.20.1 Fabric版本是0.14.22。

**Comment by LangYueMc** [comment]
模组只会添加没有 zh_cn 语言条目的，所以我能想到的你说的这个问题应该是因为汉化包不规范，直接改了 en_us 文件吧，这个没法兼容，但是你可以通过配置黑名单，把被替换的 mod 名加进黑名单里就不会覆盖了。

至于第二个问题，我没测试过 placeholder 的情况，我以为的效果是中文的正常显示，只是追加的原文会显示 %s 这样的，或者你有截图吗？

**Comment by xinpingqihe-44** [comment]
![2 X C_URS_S9H6GT`DBWZ E](https://github.com/LangYueMc/AutoTranslation/assets/145717440/1b0b030f-91d5-4ab0-8abf-b61aefcbd9f9)
![R AN NM 12Q)40V{CBR 2$D](https://github.com/LangYueMc/AutoTranslation/assets/145717440/662de385-e8bb-4fed-b903-92e087b78028)

第一张图
所有有语言(zh_cn)的模组还是被拉去汉化了一遍，我也不清楚为什么。

第二张图
就是这样，显示不出来了直接。

**Comment by LangYueMc** [comment]
第一个问题我没复现，应该是 Mod 冲突了，你有没有加什么资源加载优化相关的 Mod?
![image](https://github.com/LangYueMc/AutoTranslation/assets/19365612/e3916ec7-b1da-41d7-9f00-96d697018658)

第二个修了，等下一版
![image](https://github.com/LangYueMc/AutoTranslation/assets/19365612/d5c36c6a-4f5b-44d1-aa39-62d284a31577)

**Comment by xinpingqihe-44** [comment]
第一个问题
找到内鬼了，是一个模组引起的，叫Wurst，删掉就能正常运行。

**Comment by LangYueMc** [comment]
> 第一个问题 找到内鬼了，是一个模组引起的，叫Wurst，删掉就能正常运行。

修了，等下一版发布，或者你可以自己构建
