### ISSUE TITLE
English changelogs

### ISSUE THREAD

**Issue by bangetto** [LangYueMc/AutoTranslation#2]
Hey, I like the idea of this mod, but I don't know Chinese, so please provide English change logs too!

**Comment by LangYueMc** [comment]
感谢反馈，下一版本将有双语 CHANGELOG，但是目前版本的只能自行使用翻译引擎了。

Thanks for the feedback, the next version will have bilingual CHANGELOG, but the current version can only use the translation engine by yourself.


目前几个版本并未增加新功能，大多是修复 BUG，以及优化代码，仅图标不再一直显示在右上角了，默认仅当前屏幕按下了快捷键才会显示图标。

The current few versions have not added new features, most of them are fixing bugs and optimizing the code. Only the icon is no longer always displayed in the upper right corner. By default, the icon will only be displayed when the shortcut key is pressed on the current screen.

**Comment by LangYueMc** [comment]
Existing English version.
