### ISSUE TITLE
模组装载后出现Optifine与forge不兼容

### ISSUE THREAD

**Issue by FuXM0** [LangYueMc/AutoTranslation#8]
### Mod 加载器

Forge

### Mod 加载器版本

Forge_43.3.0-OptiFine_I2

### Minecraft 版本

1.19.2

### 本模组版本

1.0.5+mc1.19.2-forge

### latest.log

https://gist.github.com/FuXM0/557f5483e861eeca545eb916521f455d#file-gistfile1-txt

### 详细描述

[错误报告-2024-1-9_23.02.29.zip](https://github.com/LangYueMc/AutoTranslation/files/13875389/-2024-1-9_23.02.29.zip)

**Comment by LangYueMc** [comment]
抱歉，这个永远不会兼容的。主要是没办法兼容，他不开源啊。
